[2024-12-04T00:53:33.708+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-04T00:53:33.724+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.extract_tmdb_currently_playing manual__2024-12-04T00:53:32.638703+00:00 [queued]>
[2024-12-04T00:53:33.727+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_tmdb_us_movies.extract_tmdb_currently_playing manual__2024-12-04T00:53:32.638703+00:00 [queued]>
[2024-12-04T00:53:33.727+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-04T00:53:33.732+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract_tmdb_currently_playing> on 2024-12-04 00:53:32.638703+00:00
[2024-12-04T00:53:33.739+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=51361) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-04T00:53:33.740+0000] {standard_task_runner.py:63} INFO - Started process 51364 to run task
[2024-12-04T00:53:33.739+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_tmdb_us_movies', 'extract_tmdb_currently_playing', 'manual__2024-12-04T00:53:32.638703+00:00', '--job-id', '748', '--raw', '--subdir', 'DAGS_FOLDER/tmdb_historical.py', '--cfg-path', '/tmp/tmpx6mkyavj']
[2024-12-04T00:53:33.745+0000] {standard_task_runner.py:91} INFO - Job 748: Subtask extract_tmdb_currently_playing
[2024-12-04T00:53:33.767+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_tmdb_us_movies.extract_tmdb_currently_playing manual__2024-12-04T00:53:32.638703+00:00 [running]> on host bbf2723bdd9c
[2024-12-04T00:53:33.808+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_tmdb_us_movies' AIRFLOW_CTX_TASK_ID='extract_tmdb_currently_playing' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T00:53:32.638703+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T00:53:32.638703+00:00'
[2024-12-04T00:53:33.809+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-04T00:53:33.815+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-04T00:53:33.815+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tmdb_historical.py", line 35, in extract_tmdb_currently_playing
    response = requests.get(f"{url}&page={page}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '"https://api.themoviedb.org/3/movie/now_playing?api_key={api_key}&region=US"&page=1'
[2024-12-04T00:53:33.819+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_tmdb_us_movies, task_id=extract_tmdb_currently_playing, run_id=manual__2024-12-04T00:53:32.638703+00:00, execution_date=20241204T005332, start_date=20241204T005333, end_date=20241204T005333
[2024-12-04T00:53:33.823+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 748 for task extract_tmdb_currently_playing (No connection adapters were found for '"https://api.themoviedb.org/3/movie/now_playing?api_key={api_key}&region=US"&page=1'; 51364)
[2024-12-04T00:53:33.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-04T00:53:33.849+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T00:53:33.850+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
